# Purpose: Define reusable Copilot configuration profiles for different repository types.
# Notes:
# - Keep this file generic so it can be copied to unrelated teams.
# - Profiles are advisory and can be consumed by automation later.

version: 1
profiles:
  minimal:
    description: Baseline setup for small repositories.
    recommended_instructions:
      - instructions/markdown.instructions.md
      - instructions/yaml.instructions.md
      - instructions/json.instructions.md
    recommended_prompts:
      - prompts/cs-github-action.prompt.md
    recommended_skills:
      - skills/cicd-workflow/SKILL.md

  backend-java:
    description: Java service repositories.
    recommended_instructions:
      - instructions/java.instructions.md
      - instructions/github-actions.instructions.md
      - instructions/markdown.instructions.md
    recommended_prompts:
      - prompts/cs-java.prompt.md
      - prompts/cs-add-unit-tests.prompt.md
    recommended_skills:
      - skills/project-java/SKILL.md
      - skills/cicd-workflow/SKILL.md

  backend-nodejs:
    description: Node.js service repositories.
    recommended_instructions:
      - instructions/nodejs.instructions.md
      - instructions/github-actions.instructions.md
      - instructions/markdown.instructions.md
    recommended_prompts:
      - prompts/cs-nodejs.prompt.md
      - prompts/cs-add-unit-tests.prompt.md
    recommended_skills:
      - skills/project-nodejs/SKILL.md
      - skills/cicd-workflow/SKILL.md

  infrastructure-heavy:
    description: Infrastructure repositories with Terraform as primary language.
    recommended_instructions:
      - instructions/terraform.instructions.md
      - instructions/github-actions.instructions.md
      - instructions/yaml.instructions.md
    recommended_prompts:
      - prompts/cs-terraform.prompt.md
      - prompts/cs-cloud-policy.prompt.md
    recommended_skills:
      - skills/terraform-feature/SKILL.md
      - skills/terraform-module/SKILL.md
      - skills/cloud-policy/SKILL.md

  mixed-platform:
    description: Repositories mixing app code, CI/CD, and some infrastructure.
    recommended_instructions:
      - instructions/java.instructions.md
      - instructions/nodejs.instructions.md
      - instructions/github-actions.instructions.md
      - instructions/terraform.instructions.md
    recommended_prompts:
      - prompts/cs-java.prompt.md
      - prompts/cs-nodejs.prompt.md
      - prompts/cs-github-action.prompt.md
      - prompts/cs-terraform.prompt.md
    recommended_skills:
      - skills/project-java/SKILL.md
      - skills/project-nodejs/SKILL.md
      - skills/cicd-workflow/SKILL.md
      - skills/terraform-feature/SKILL.md
